### ISSUE TITLE
Two Questions

### ISSUE THREAD

**Issue by garsdle** [layoutBox/FlexLayout#100]
1. Do you support or plan on supporting macOS?
2. What would you tell a dev that is on the fence between FlexLayout and LayoutKit for a bigger project?

Finally I love your work and the performance benchmarks. Thanks for putting creating this, I've already used it on a smaller project and it's fantastic!

Cheers!
Manny

**Comment by garsdle** [comment]
Actually a quick third question :).
3. I noticed that even though sometimes I use addItem just for layout it adds a UIView with subviews. Wouldn't it actually increase performance even more to have some sort of addLayoutItem that just keeps tracks of layout and doesn't add a UIView? Not sure if that makes sense.

**Comment by lucdion** [comment]
1) Yoga doesn't yet support macOS, so FlexLayout doesn't too. Sorry.
2) To be honest, I'm a little bit disappointed by the Yoga's project. Issues are not always handled rapidly. I think that LayoutKit is more highly maintained. But my personal choice is still PinLayout 🙂
3) You're probably right, even if I didn't benchmark it. It is 1% faster or 5% fasters, its really hard to know.

**Comment by garsdle** [comment]
Nice! thanks for all the answers. I do love pin layout 🙂

Cheers!
