### ISSUE TITLE
macOS support?

### ISSUE THREAD

**Issue by leotumwattana** [layoutBox/FlexLayout#105]
Hi,

First off, wonderful library. 

Was wondering if you plan to add support for macOS similar to PinLayout having support for macOS?

**Comment by lucdion** [comment]
Hi @leotumwattana, there is no plan for now, it would be interesting, but I don't currently have enough time to do this 🙁. But I'll keep this topic open.

**Comment by garsdle** [comment]
I think this is a really interesting idea. I've recently been toying with the idea of abstracting my layout to increase the parts of my app that are platform agnostic. I'm actually thinking beyond macOS... Anyways I would be down to help you make it happen @lucdion . Probably needs some good thought first.

**Comment by ngocdaothanh** [comment]
PinLayout supports Mac, so it's wonderful if FlexLayout also supports Mac.

**Comment by zl00** [comment]
@leotumwattana 
Do you find the solution for macOS?

**Comment by leotumwattana** [comment]
I ended up going with PinLayout.
