### ISSUE TITLE
Getting issue while exporting to IPA (carthage and bitcode)

### ISSUE THREAD

**Issue by rajeshchilukuri** [layoutBox/FlexLayout#106]
I am getting below Error while i export to IPA.

Failed to verify bitcode in FlexLayout.framework/FlexLayout:
error: Cannot extract bundle from /var/folders/ww/nzb88by17dxg0bxns_9zncfc0000gn/T/XcodeDistPipeline.IU0/Root/Payload/SampleApp.app/Frameworks/FlexLayout.framework/FlexLayout (i386)

**Comment by lucdion** [comment]
@rajeshchilukuri I currently don't know what is causing this error 🙁 Have you found a solution?

**Comment by rajeshchilukuri** [comment]
<img width="717" alt="screen shot 2018-08-07 at 10 09 22 pm" src="https://user-images.githubusercontent.com/40469577/43781091-b41c1b24-9a8e-11e8-8d80-9a7138e983f1.png">
I unchecked these options and then it worked. Not sure why it was giving an error when these two were selected.

**Comment by rajeshchilukuri** [comment]
You can mark this as closed as it worked for me.

**Comment by linqingmo** [comment]
I found it in Distribution Guide–App Thinning:
Including bitcode will allow Apple to re-optimize your app binary in the future without the need to submit anew version of your app to the store.

I think it's better to rebuild from Bitcode.
I upload my project with bitcode. To enable bitcode for your framework and your project, you will need additional work not just set ENABLE_BITCODE = YES, you also need to add a User-Defined setting BITCODE_GENERATION_MODE = bitcode.

[https://stackoverflow.com/questions/36184930/xcodebuild-7-3-cant-enable-bitcode](https://stackoverflow.com/questions/36184930/xcodebuild-7-3-cant-enable-bitcode)
