### ISSUE TITLE
scrollview help

### ISSUE THREAD

**Issue by ChendayUP** [layoutBox/FlexLayout#110]
I have a contentView, contentView have a scrollview, code is below, but scrollview frame is larger than contentView, not equal contentView height, how can I do?
```
 addSubview(contentView)
        contentView.flex
            .direction(.column)
            .padding(23, 16, 23, 16)
            .define { (flex) in
                flex.addItem(scrollView).define({ (flex) in
                    for item in list {
                        let view = VoteTextSelectRow(state: item)
                        flex.addItem(view).marginTop(26)
                    }
                    flex.addItem().height(80)
                })
                
        }
```

**Comment by VincentSit** [comment]
Hi @ChendayUP,

I think you may need to set the `scrollView`'s contentSize.

Please check the [`RaywenderlichTutorialView `](https://github.com/layoutBox/FlexLayout/blob/fb1ed06dc26b81347a379eb334727030d4a6de8d/Example/FlexLayoutSample/UI/Examples/RaywenderlichTutorial/RaywenderlichTutorialView.swift) in Example out.


https://github.com/layoutBox/FlexLayout/blob/fb1ed06dc26b81347a379eb334727030d4a6de8d/Example/FlexLayoutSample/UI/Examples/RaywenderlichTutorial/RaywenderlichTutorialView.swift#L20-L21

https://github.com/layoutBox/FlexLayout/blob/fb1ed06dc26b81347a379eb334727030d4a6de8d/Example/FlexLayoutSample/UI/Examples/RaywenderlichTutorial/RaywenderlichTutorialView.swift#L134-L136

https://github.com/layoutBox/FlexLayout/blob/fb1ed06dc26b81347a379eb334727030d4a6de8d/Example/FlexLayoutSample/UI/Examples/RaywenderlichTutorial/RaywenderlichTutorialView.swift#L147-L159

**Comment by lucdion** [comment]
Closing this issue
