### ISSUE TITLE
Conflict with rn yoga

### ISSUE THREAD

**Issue by zhuruliang** [layoutBox/FlexLayout#112]
RN needs to pod import yoga file with conflict with the file in FlexLayout, do you have some solutions?

**Comment by zhuruliang** [comment]
I've add `spec.xcconfig = { 'USER_HEADER_SEARCH_PATHS' => '"${PROJECT_DIR}/Sources/.."/**' }` in podspec file to solve this issue. should I commit a pr for this?

**Comment by lucdion** [comment]
Hi @zhuruliang, sorry for the delay, but there is no plan to support that. I think you should use the RN  yoga's Objective-C  interface. It would be really difficult to support simultaneously two version of yoga in a single app.

**Comment by HParis** [comment]
@lucdion Can I rename the Yoga file, class, enum to solve this problem? Like below:
```
YG -> RYG
Yogo -> RYogo
```

![image](https://user-images.githubusercontent.com/4798443/65016311-84352100-d956-11e9-864b-0ffcb3662655.png)
