### ISSUE TITLE
Writing custom views for use in flex layouts

### ISSUE THREAD

**Issue by jwells89** [layoutBox/FlexLayout#113]
Hello,

I've been exploring the use of this library and something that isn't quite clear to me is how to properly set up custom UIView subclasses for use in larger parent flex layouts – primarily, what properties/methods one should override in order for the parent layout to properly size and place these views.

I've sifted through the examples and docs and haven't found anything that elaborates on this subject, with the focus seemingly mostly being on using UIKit-provided primitives (UILabel, UIButton, etc) in layouts. Have I missed anything?

Thanks!

**Comment by lucdion** [comment]
Hi @jwells89, you're right that there is no example showing. I will add one shortly.

To support that, your custom view only needs to implement the `UIView.sizeThatFits(:CGSize)` method. FlexLayout will call this method to get the space required by your custom view matching the available space (size parameter).

If you custom use FlexLayout too, you can use the `flex.sizeThatFits(...)` method to ask FlexLayout to compute the size of your custom view.

**Comment by jwells89** [comment]
@lucdion Perfect, thank you!

One thing that tripped me up a bit and might be mentioning for anybody reading this in future is that for custom views intended for use in flex layout table view cells, overriding `layoutSubviews()` and requesting a layout with `flex.layout()` isn't necessary can even cause problems – in my case, the subviews would layout out in their parent flex row properly at first, but the row would "collapse" and pile the views on top of each when any of the cells were selected. After removing the override and only implementing `sizeThatFits(…)` everything works as expected.

**Comment by lucdion** [comment]
@jwells89 you're right. If you'd like, you can modify the sample app and update the code. I would be more than happy to approve the PR 🙂

**Comment by Coder-XI** [comment]
The same question here, in some case, I have to remove overriding layoutSubviews() in subviews or else  the frame of subviews are incorrect.
Can u tell me what cause this?

**Comment by linqingmo** [comment]
@Coder-XI You can have a look at YGLayout.mm,
```objective-c
static void YGApplyLayoutToViewHierarchy(UIView *view, BOOL preserveOrigin)
{
  NSCAssert([NSThread isMainThread], @"Framesetting should only be done on the main thread.");

  const YGLayout *yoga = view.yoga;

  if (!yoga.isIncludedInLayout) {
     return;
  }

  YGNodeRef node = yoga.node;
  const CGPoint topLeft = {
    YGNodeLayoutGetLeft(node),
    YGNodeLayoutGetTop(node),
  };

  const CGPoint bottomRight = {
    topLeft.x + YGNodeLayoutGetWidth(node),
    topLeft.y + YGNodeLayoutGetHeight(node),
  };

  const CGPoint origin = preserveOrigin ? view.frame.origin : CGPointZero;
  view.frame = (CGRect) {
    .origin = {
      .x = YGRoundPixelValue(topLeft.x + origin.x),
      .y = YGRoundPixelValue(topLeft.y + origin.y),
    },
    .size = {
      .width = YGRoundPixelValue(bottomRight.x) - YGRoundPixelValue(topLeft.x),
      .height = YGRoundPixelValue(bottomRight.y) - YGRoundPixelValue(topLeft.y),
    },
  };

  if (!yoga.isLeaf) {
    for (NSUInteger i=0; i<view.subviews.count; i++) {
      YGApplyLayoutToViewHierarchy(view.subviews[i], NO);
    }
  }
}
```
It has set up subviews, so you shouldn't write `layoutSubviews()` in subviews.

**Comment by philipbel** [comment]
I, too, got tripped by this.

If I understand @lucdion correctly, only the top-level view should implement `layoutSubviews()` (or `viewDidLayoutSubviews()` for view controllers).
But what about reusable views (and, in particular, reusable view controllers by means of`UIViewController.addChild(:)`)?

**Comment by rakeshashastri** [comment]
> Hi @jwells89, you're right that there is no example showing. I will add one shortly.
> 
> To support that, your custom view only needs to implement the `UIView.sizeThatFits(:CGSize)` method. FlexLayout will call this method to get the space required by your custom view matching the available space (size parameter).
> 
> If you custom use FlexLayout too, you can use the `flex.sizeThatFits(...)` method to ask FlexLayout to compute the size of your custom view.

Is there an example for how to implement `sizeThatFits`?
