### ISSUE TITLE
Fully reset/remake constraints

### ISSUE THREAD

**Issue by jordanebelanger** [layoutBox/FlexLayout#115]
I'd like to fully reset all constraints created on a flex container in a similar fashion to how Snapkit works when you call `remakeConstraints:` instead of `makeConstraints:`.

**Comment by lucdion** [comment]
Hi @jordanebelanger, what would be the expected behavior?

- Reset all item properties (direction, justifyContent, alignItems, grow, shrink, ...)_
- Remove all its child items
- All of the above

**Comment by jordanebelanger** [comment]
Yes I did not think about the effect on subviews (added from addItem(:) calls) until earlier today.

Good question :)

I feel like neither really makes sense at first glance. I would say a reset of all the proprieties affecting only the element the call is made on, not its subviews, would make the most sense.
