### ISSUE TITLE
Wrong Default value in `func shrink(_:)` FlexLayout.swift

### ISSUE THREAD

**Issue by mqzkim** [layoutBox/FlexLayout#118]
Default value might be 0

https://github.com/layoutBox/FlexLayout/blob/64aa1053376b4662f085ff91e40464e4ac07f69b/Sources/FlexLayout.swift#L310

**Comment by lucdion** [comment]
Fixed in release 1.3.2: https://github.com/layoutBox/FlexLayout/releases/tag/1.3.12
