### ISSUE TITLE
Force to Re-layout

### ISSUE THREAD

**Issue by BeerPoldet** [layoutBox/FlexLayout#124]
Is there a way to force flex to re-layout all of its children?

I have scenario where sometime it's better to just tell flex to re-calculate and layout all of its children than to mark each of children as dirty.

**Comment by BeerPoldet** [comment]
@lucdion do you know if yoga already provide this kind of mechanic? or it's flexlayout it self has to find the way to perform this.

**Comment by lucdion** [comment]
@BeerPoldet, no Yoga doesn't support that. But it would be totally possible to implement this in flexlayout.
