### ISSUE TITLE
Grow setting not recalculated properly when orientation changes?

### ISSUE THREAD

**Issue by SilverTab** [layoutBox/FlexLayout#125]
I have a fixed-size column flex container that has 4 subviews; 3 which are of fixed height, and 1 that should fill the rest of the available space (using `.grow(1)` ). The layout looks perfectly fine, but if I rotate the device and change the orientation the "growable" section stays the same size and it messes up the layout. Am I forgetting something in `layoutSubviews`?  Any help would be appreciated.

Not really easy to describe so here's a very simple example that demonstrates the issue:

    class MainView: UIView {
        fileprivate let rootFlexContainer = UIView()

        init() {
            super.init(frame: .zero)
            backgroundColor = .red
            rootFlexContainer.backgroundColor = .white

            rootFlexContainer.flex.direction(.column).padding(16).define { flex in
                // 2 views
                flex.addItem().backgroundColor(.blue).height(50).marginBottom(16)
                flex.addItem().backgroundColor(.blue).height(50).marginBottom(16)

                // Growing item
                flex.addItem().backgroundColor(.blue).grow(1).marginBottom(16)

                // button that sticks to the bottom (using views for example purposes)
                flex.addItem().backgroundColor(.blue).height(50)

            }

            addSubview(rootFlexContainer)

        }

        required init?(coder aDecoder: NSCoder) {
            fatalError("init(coder:) has not been implemented")
        }

        override func layoutSubviews() {
            super.layoutSubviews()
            rootFlexContainer.pin.all(pin.safeArea)
            rootFlexContainer.flex.layout()

        }

    }

**Comment by linqingmo** [comment]
add `shrink(1)` to the third one.
```swift
rootFlexContainer.flex.direction(.column).padding(16).define { (flex) in
     flex.addItem().backgroundColor(.blue).height(50).marginBottom(16)
     flex.addItem().backgroundColor(.blue).height(50).marginBottom(16)
     flex.addItem().backgroundColor(.blue).shrink(1).grow(1).marginBottom(16)
     flex.addItem().backgroundColor(.blue).height(50)
}
```

**Comment by SilverTab** [comment]
Gah... I swear I ran into this exact issue before but just couldn't remember the solution 🤦‍♂️

Thanks for your help! This indeed does exactly what I need!

**Comment by tylerlantern** [comment]
Thx This save me a Lot.
