### ISSUE TITLE
UICollectionView with auto-sized cell.

### ISSUE THREAD

**Issue by sLm-s** [layoutBox/FlexLayout#127]
Hello. How with help Flex, you can create a collection within another collection and both with an auto-sized cell.
I wrote an example, but I think that all this can be written differently. Can you help and improve the code?
[UICollectionViewCell-dynamic-height.zip](https://github.com/layoutBox/FlexLayout/files/3141748/UICollectionViewCell-dynamic-height.zip)

**Comment by lucdion** [comment]
Very old topic. Closing it.
