### ISSUE TITLE
Tableview hight is incorrect

### ISSUE THREAD

**Issue by hirenshah22887** [layoutBox/FlexLayout#130]
Hi,

Facing issue with UITebleView height. Height of table view is calculated based on estimatedRowHeight, even if cell size is big or small.

For example is there are two rows with dynamic height, and estimatedRowHeight = 40.
Then table view size is fixed to 80 only. even if cell are of height 30,40  respectively size of table view should be 70 only.

cells are getting correct height but it add space for remaining space, and table height is bigger.

**Comment by lucdion** [comment]
Closing this 3 years old question.
