### ISSUE TITLE
IOS FlexLayout ignores vertical constraint goes out of container

### ISSUE THREAD

**Issue by amodkanthe** [layoutBox/FlexLayout#133]
`tagsView.willRemoveSubview(rootFlexContainer)
    tagsView.addSubview(rootFlexContainer)

     rootFlexContainer.flex.direction(.rowReverse).wrap(.wrap).alignSelf(.stretch).justifyContent(.start).paddingRight(5).define { (flex) in
        for i in 0..<(array.count > 3 ? 3 : array.count) {
            let nameLabel = TagLabel()
            //nameLabel.lineBreakMode = .byCharWrapping
            nameLabel.font = FontStyle.ProximaNovaRegular(size: 12)
            nameLabel.layer.borderColor = UIColor.hexStringToUIColor(hex: TravelXStrings.grayBorderColor).cgColor
            nameLabel.layer.cornerRadius = 5
            nameLabel.layer.borderWidth = 1.0
            nameLabel.textColor = .black
            nameLabel.text = " "+array[i]+" "
            //nameLabel.sizeToFit()
            flex.addItem(nameLabel).margin(2)
        }
        tagsView.flex.layout(mode: .fitContainer)
    }

override func layoutSubviews() {
    super.layoutSubviews()
    layout()
}

fileprivate func layout() {
    tagsView.flex.layout(mode: .fitContainer)
    //tagsView.flex.layout(mode: .adjustWidth)
}`

<img width="337" alt="Screenshot 2019-06-20 at 2 40 56 PM" src="https://user-images.githubusercontent.com/5066441/59841458-fc993f80-9371-11e9-9777-9e183f4426ab.png">

**Comment by lucdion** [comment]
Closing this 3 years old question.
