### ISSUE TITLE
How to add spacing between flex items?

### ISSUE THREAD

**Issue by abhisood** [layoutBox/FlexLayout#134]
Currently I am achieving it via combination of margin on inner view and spacer-views
I have following UI structure in a height adjustable `UITableViewCell`.
```
        let textContainer = UIView()
       // .spaceBetween doesn't seem to add any space here. 
        textContainer.flex.direction(.column).alignItems(.start).justifyContent(.start).define { flex in
            flex.addItem(tickerContainer).grow(1)
            flex.addItem(titleLabel).grow(1).marginVertical(8)
            flex.addItem(subtitleLabel).grow(1)
        }

        flex.direction(.row).padding(8).justifyContent(.start).define { flex in
            flex.addItem(imageView).aspectRatio(4.0 / 3)
            flex.addItem().size(8) // Spacer view
            flex.addItem(textContainer).grow(1).shrink(1)
        }
```
Using spacer view is good because if I change the `flex.direction` to `.column` dynamically, the spacer view still works as expected. 
My concern with using spacer-views and margins is that we need the ability to hide certain labels. In that case UI won't be consistent anymore because margins will be hidden and/or spacer view should be hidden as well.

What are some of the easier ways to handle this?

**Comment by wjling** [comment]
Why not try margin methods? e.g marginLeft(..), marginRight(..)

**Comment by iWECon** [comment]
maybe, you can add an extension for  Flex:
`
extension Flex {
    
    @discardableResult
    func horizontallySpacing(_ value: CGFloat?) -> Flex {
        guard let view = view, view.subviews.count > 1 else { return self }
        for (idx, subview) in view.subviews.enumerated() {
            if idx == 0 { continue }
            subview.flex.marginLeft(value ?? 0)
        }
        return self
    }
    
    @discardableResult
    func verticallySpacing(_ value: CGFloat?) -> Flex {
        guard let view = view, view.subviews.count > 1 else { return self }
        for (idx, subview) in view.subviews.enumerated() {
            if idx == 0 { continue }
            subview.flex.marginTop(value ?? 0)
        }
        return self
    }
}

`

**Comment by abhisood** [comment]
@iWECon - That looks like an acceptable solution.
