### ISSUE TITLE
Why not use Bool value as parameter in display(..) 

### ISSUE THREAD

**Issue by wjling** [layoutBox/FlexLayout#143]
Just asking. If taking `Bool` as parameter we can use this function as we use `isHidden` property in `UIView`. It will be more convenient I think.

**Comment by lucdion** [comment]
Sorry @wjling, I'm not sure to understand your comment 🤔

**Comment by wjling** [comment]
Sorry I don't express myself clearly. I just think about that if the API is designed as `display(true)` or `display(false)`, it may be clearer and more convenient than `display(.none)` and `display(.flex)`. Never mind, I'm just a little curious :D

**Comment by okaverin** [comment]
`display: flex` is Flexbox CSS syntax. `flex` and `none` come from Yoga. I guess the API is just trying to be true to that.

**Comment by lucdion** [comment]
Very old topic. Closing it.
