### ISSUE TITLE
SPM support

### ISSUE THREAD

**Issue by zdnk** [layoutBox/FlexLayout#144]
Hello,

any plans to support Swift Package Manager soon?

**Comment by simdani** [comment]
SPM support would be awesome!

**Comment by AivarasGus** [comment]
YES, please!

**Comment by lucdion** [comment]
That would really nice indeed but I would need help to do this, I don't have enough time for this feature 😔

**Comment by gcox** [comment]
@zdnk @simdani @AivarasGus @lucdion PR #150 adds SPM support. Confirmation that it works for other folks would be appreciated.
