### ISSUE TITLE
Auto Resize!

### ISSUE THREAD

**Issue by VasilisLule** [layoutBox/FlexLayout#149]
![Στιγμιότυπο 2019-10-30, 9 03 51 μμ](https://user-images.githubusercontent.com/56849179/67890220-f9506480-fb58-11e9-8575-588cc408b779.png)
![Στιγμιότυπο 2019-10-30, 9 03 03 μμ](https://user-images.githubusercontent.com/56849179/67890238-01100900-fb59-11e9-8e98-cb58a880ce1d.png)

I have a selector and when i switch accountypes i want to hide 2certain textFields and the others come to Top. 
Any ideas?

**Comment by lucdion** [comment]
You need to relayout the Flex container, i.e. do what you probably do in your `UIView.layoutSubviews()` or `UIViewController.viewDidLayoutSubviews()`.

**Comment by marcuswu0814** [comment]
Hi @lucdion, similar problem here, I had a button component that self size when label text changed. And I need the container relayout when subview's size changed. (dynamic container size) 

Currently I call `self.superview.flex.layout()` in my component but I don't think it's a good idea.

## Some question:

Q1: What's is best practice to notify the `flexContainer` which is the component's super view?
Q2: If no better solution, how to implement the requirement with `PinLayout`? 

Could you please give me some tips or suggestion to resolve it. 🙏
If need much more info or need to create a separate issue, feel free to let me know, thanks. 😃

**Comment by Abdul-Quadri-Ismail** [comment]
After facing  the auto resize issue on flexLayout.
I Tried using YogaKit directly maybe the behaviour will be different however am still seeing the same issue.

**Comment by Abdul-Quadri-Ismail** [comment]
i had to reload the view controller when ever i need to update the container

**Comment by lucdion** [comment]
Very old topic. Closing it.
