### ISSUE TITLE
How to introduce swift in oc project FlexLayout ,like pinLayout

### ISSUE THREAD

**Issue by chongbo2013** [layoutBox/FlexLayout#156]
![image](https://user-images.githubusercontent.com/3191545/78109638-2cf72980-742c-11ea-86c3-c1ef26337ab7.png)
![image](https://user-images.githubusercontent.com/3191545/78109660-3aacaf00-742c-11ea-8d39-e8e180dbfa4a.png)
I have introduced the project but I don't know how to call the method。
![image](https://user-images.githubusercontent.com/3191545/78109743-60d24f00-742c-11ea-9f4b-fe9bab0b72d1.png)

pinLayout I have introduced and used correctly, but FlexLayout cannot be called

**Comment by chongbo2013** [comment]
PinLayoutObjC

**Comment by lucdion** [comment]
Very old topic. Closing it.
