### ISSUE TITLE
No versions of FlexLayout match the requirement

### ISSUE THREAD

**Issue by nachonavarro** [layoutBox/FlexLayout#157]
I followed the steps in the README to add this library as a dependency via SPM, but I'm getting
the following error in xcode:

![Screen Shot 2020-05-01 at 12 49 42](https://user-images.githubusercontent.com/15170903/80800636-3c43d100-8baa-11ea-8142-d010e8cb2400.png)

When I put version 1.3.17 instead of 1.3.18 like this:
```swift
dependencies: [
    .package(url: "https://github.com/layoutBox/FlexLayout.git", from: "1.3.17")
],
```
It simply says that it can't find the manifest file.

Any ideas?
Thanks!

**Comment by lucdion** [comment]
You should use the version 1.3.18. I have just created the tag (https://github.com/layoutBox/FlexLayout/releases/tag/1.3.18)

Could you retry?
