### ISSUE TITLE
Support first baseline and last baseline item alignment

### ISSUE THREAD

**Issue by rantingmong** [layoutBox/FlexLayout#158]
Hello!

Just as the title suggests, currently FlexLayout does not support aligning of items through their first or last baseline.

As far as I know raw yoga includes function for providing the position for the first and last baseline.

Is this currently on the roadmap? If not, I can add support for this and make a pull request.

Many thanks!

**Comment by lucdion** [comment]
Hi @rantingmong, there is no plan to add that support. We will be glad to review your PR 🙂

**Comment by rantingmong** [comment]
PR is up! #159
