### ISSUE TITLE
Try to integrate flexbox layout am getting this error. "No such module 'FlexLayoutYogaKit'"

### ISSUE THREAD

**Issue by Rameshmca13** [layoutBox/FlexLayout#160]
Try to integrate flexbox layout am getting this error. "No such module 'FlexLayoutYogaKit". Without SPM i want .. Is there any way use flexbox without SPM

**Comment by lucdion** [comment]
Yes, you can use cocoapods or carthage, see https://github.com/layoutBox/FlexLayout#installation

**Comment by Rameshmca13** [comment]
is there any way to integrate flux layout without integrating via Cathrage , pod or SPM
