### ISSUE TITLE
is there any way to integrate flux layout without integrating via Cathrage , pod or SPM Because using flexbox we are trying to create one framework , I want to support both Swift and objective c

### ISSUE THREAD

**Issue by Rameshmca13** [layoutBox/FlexLayout#161]
is there any way to integrate flux layout without integrating via Cathrage , pod or SPM
Because using flexbox we are trying to create one framework , I want to support both Swift and objective c

**Comment by lucdion** [comment]
Yes, it would be possible, you can integrate FlexLayout sources code in any framework, but for doing this you will have to fork your own repo and do whatever changes required for this to work. There is no built-in solution for your case.
