### ISSUE TITLE
Need you expertise help in Configuring Auto Width and Height for UITableViewCell is it possible to configure Auto Width for a UITableviewCell and based on that the UITableView is determined. In one of our scenario we are having a situation where we need to determine the width of the Table with respect to it cell. Can you please help us to achieve this use case with flex box

### ISSUE THREAD

**Issue by Rameshmca13** [layoutBox/FlexLayout#173]
Need you expertise help in Configuring Auto Width and Height for UITableViewCell
is it possible to configure Auto Width for a UITableviewCell and based on that the UITableView is determined. In one of our scenario we are having a situation where we need to determine the width of the Table with respect to it cell. Can you please help us to achieve this use case with flex box

**Comment by lucdion** [comment]
Very old topic. Closing it, sorry
