### ISSUE TITLE
Is possible to use this with SwiftUI?

### ISSUE THREAD

**Issue by mamcx** [layoutBox/FlexLayout#174]
Or will be in the near future?

**Comment by lucdion** [comment]
That would be really nice. But there is currently no plan for that. 
SwiftUI already has `HStack` and `VStack`, I didn't have the time to check it, but I hope they make it good this time (compared to the extra limited `UIStackView`)

**Comment by mamcx** [comment]
Yeah I know, the problem is to map both. I'm slowly trying to decipher how convert one in the other and is certainly not easy!

**Comment by tigerAndBull** [comment]
> Yeah I know, the problem is to map both. I'm slowly trying to decipher how convert one in the other and is certainly not easy!

Have you found a better plan? I tried to translate, but the layout of swiftUI is very unique. 
And VStack does not support reuse cell. LazyVStack has a bug of jumping up and down.
