### ISSUE TITLE
Why Use an Old Version of Yoga?

### ISSUE THREAD

**Issue by philipbel** [layoutBox/FlexLayout#177]
Hello.

I am exploring FlexLayout (thanks for the great work!), and have noticed that an old version of Yoga from 2008 is used (facebook/yoga@295d111f0eafd9275bc4a9e8e646dbcdd5e88c2d) whereas Yoga has had many changes since then (600+ as of today):
```bash
% git log --oneline  295d111f0eafd9275bc4a9e8e646dbcdd5e88c2d..master  | wc -l
     613
```

I am wondering—why use an old version?

**Comment by philipbel** [comment]
I did some digging—it should be possible to consume YogaKit via CocoaPods (SPM not supported).

**Comment by cielpy** [comment]
Probably cause this project is less maintained, you can create a PR if you want.

**Comment by lucdion** [comment]
Updated to Yoga 2.0 recently
