### ISSUE TITLE
error: 'YGEnums.h' file not found

### ISSUE THREAD

**Issue by kimxwan0319** [layoutBox/FlexLayout#200]
I installed the FlexLayout with SPM.
And xcode occur this error.
<img width="1082" alt="sdfsdf" src="https://user-images.githubusercontent.com/67373938/164431413-f100c264-6cca-4d41-8d1e-3eeed5ff838e.png">
What should I do??

**Comment by kimxwan0319** [comment]
The error disappeared when I switched to CocoaPods, 
but I still wonder why the error occurred when I install it with SPM.

**Comment by woohyunjin06** [comment]
You should to do following steps to use FlexLayout with SPM.

```
In an Xcode target
To integrate FlexLayout into an Xcode target, use the File -> Swift Packages -> Add Package Dependency menu item.
Add "FLEXLAYOUT_SWIFT_PACKAGE=1" to the Xcode target's GCC_PREPROCESSOR_DEFINITIONS build setting. (TARGET -> Build Settings -> Apple Clang-Preprocessing -> Preprocessor Macros)
```

It is also described in README.

**Comment by kimxwan0319** [comment]
Oh, thanks..!
I didn't check readme completely...
