### ISSUE TITLE
Pods/FlexLayout/Sources/yoga/Yoga-internal.h:9:10: 'algorithm' file not found

### ISSUE THREAD

**Issue by dushandz** [layoutBox/FlexLayout#206]
My Podfile use #use_frameworks! 
add  `:modular_headers => true` in tail  Pod 'Flexlayout'
after pod install. 
Pods/FlexLayout/Sources/yoga/Yoga-internal.h:9:10: error: 'algorithm' file not found
#include <algorithm>
         ^
<unknown>:0: error: could not build Objective-C module 'FlexLayout'

Xcode: Version 13.4.1 (13F100)
MacOS: 12.4 M1

**Comment by Yurlagin** [comment]
I faced with the same issue

**Comment by michelleyin96** [comment]
I have the same issue. Did you guys resolve?

**Comment by sergeymild** [comment]
I have the same error, when adding FlexLayout pod as dependency to another pod

**Comment by gssdromen** [comment]
same issue here, any update?

**Comment by lucdion** [comment]
Fixed
