### ISSUE TITLE
FlexLayout package does not build with SwiftPM

### ISSUE THREAD

**Issue by auramagi** [layoutBox/FlexLayout#217]
SwiftPM builds are broken with `1.3.28` release, more specifically since #213.

Building produces the following error: 
- `Switch must be exhaustive` 
    [FlexLayout.swift:187](https://github.com/layoutBox/FlexLayout/blob/efff66866862d678f402c5aa41304e7a6e998a71/Sources/Swift/FlexLayout.swift#L187)

This can be reproduced in the example project. Note that builds with CocoaPods are not affected.
In my limited looking into this problem, this seems to be caused by enums being treated differently for SwiftPM (controlled by `FLEXLAYOUT_SWIFT_PACKAGE` in [FlexLayout+Enum.swift](https://github.com/layoutBox/FlexLayout/blob/efff66866862d678f402c5aa41304e7a6e998a71/Sources/Swift/Impl/FlexLayout%2BEnum.swift)).

![221505212-80f67563-e6be-4567-a525-5b4eb3a5569c](https://user-images.githubusercontent.com/38748295/221747313-d6537c7c-25ec-475c-a2de-5f5343576c91.png)

Environment:
    - Xcode 14.2

**Comment by lucdion** [comment]
Sorry, this has been fixed in the new release 1.3.29
