### ISSUE TITLE
'YGEnums.h' file not found - When adding FlexLayout as dependency of another Swift Package.

### ISSUE THREAD

**Issue by lukewakeford** [layoutBox/FlexLayout#219]
I'm following [installation steps](https://github.com/layoutBox/FlexLayout#another-swift-package) to add FlexLayout to **"Another Swift Package" not to an Xcode Project**.

I have defined the dependency in my Package.swift as:
```
.package(
    url: "https://github.com/layoutBox/FlexLayout", "1.3.29"..<"2.0.0"
),
```
and linked it to my target
```
dependencies: [
    "FlexLayout",
    ...
]
```
The package resolves fine but errors when building with 
> 'YGEnums.h' file not found

As far as I can see there is no way of adding `GCC_PREPROCESSOR_DEFINITIONS` in `Package.swift`

**Comment by lucdion** [comment]
Sorry, I haven't try that before. If you find a solution, please tell us, we will add it to the documentation.

**Comment by lukewakeford** [comment]
I don't think there is a solution - the documentation may need updating to reflect that 😞

**Comment by PetrosTepoyan** [comment]
Same

**Comment by lukewakeford** [comment]
I take it back, looks like there is a fix! I was able to get SPM to build FlexLayout as a dependency by swapping to use the built in preprocessor definition `SWIFT_PACAKAGE` which means the yoga imports are now located correctly.

**Comment by lucdion** [comment]
@lukewakeford, would you accept to update the documentation that explains what you have done? 🙏

**Comment by lucdion** [comment]
Fix in the release https://github.com/layoutBox/FlexLayout/releases/tag/1.3.30

**Comment by sergeymild** [comment]
any progress? because it doesn't work, i have tried to add Flexlayout as dependency to another Swift package and have got these errors 
<img width="360" alt="Screenshot 2023-08-15 at 4 31 25 AM" src="https://github.com/layoutBox/FlexLayout/assets/3685209/3c1805d2-b888-4545-94c4-13f20d11d734">

**Comment by lukewakeford** [comment]
You have to add the flag in the target settings, see here: https://github.com/layoutBox/FlexLayout/pull/226#issuecomment-1597116005

**Comment by sergeymild** [comment]
it is not SwiftPackage it is Pod
