### ISSUE TITLE
Use of bitwise '|' with boolean operands

### ISSUE THREAD

**Issue by RachikAbidi** [layoutBox/FlexLayout#224]
![Capture d’écran 2023-04-03 à 14 51 58](https://user-images.githubusercontent.com/33457873/229515031-a340c2be-124a-4093-92a4-5004c2cda832.png)
Xcodebuild fail with swift 5.8
Need to replace `|` with `||`

**Comment by sivrish** [comment]
Facing the same issue.

**Comment by MikePetitfils** [comment]
Same here.

**Comment by KimHyunMin1751** [comment]
Same here.

**Comment by lucdion** [comment]
This is now fixed with version 1.3.31
