### ISSUE TITLE
Flexbox gap of Yoga in FlexLayout?

### ISSUE THREAD

**Issue by Robotxm** [layoutBox/FlexLayout#235]
Yoga v2.0.0 introduced [flexbox gap](https://github.com/facebook/yoga/releases/tag/v2.0.0). Is there any possible for FlexLayout to support this feature?

**Comment by Skyline-23** [comment]
I requested PR for this issue

**Comment by lucdion** [comment]
Your fix has been [released](https://github.com/layoutBox/FlexLayout/releases/tag/2.0.05). Thanks for this change
