### ISSUE TITLE
New version format breaks SwiftPM resolution

### ISSUE THREAD

**Issue by brentleyjones** [layoutBox/FlexLayout#253]
SwiftPM treats `2.0.07` and `2.0.7` the same (incorrectly), which means the new `2.0.7` release breaks it for people depending on `2.0.07`:

```
error: 'flexlayout': Revision fcb3e7940948abf02cd5b7205e53e870d7a73401 for flexlayout remoteSourceControl https://github.com/layoutBox/FlexLayout version 2.0.7 does not match previously recorded value ad20f2874f0fe87300e89caed2f03d5c9525c3c0
```

Can that release be pulled, and re-published as `2.0.08` or `2.0.8`?

**Comment by lucdion** [comment]
I have created a new 2.0.8 release

**Comment by OhKanghoon** [comment]
hi @lucdion 

Could you remove the newly added 2.0.8 release and tag?
It conflicts with the existing '2.0.08' version and affect breaking changes to the spm user
