### ISSUE TITLE
SPM Load Error!!!

### ISSUE THREAD

**Issue by CtrlJone** [layoutBox/FlexLayout#258]
<img width="471" alt="image" src="https://github.com/user-attachments/assets/79453147-ad50-4ac0-aeea-20ecf4a1f897">
@heoblitz Could you help check it out?

**Comment by heoblitz** [comment]
FlexLayout is currently only supported on iOS. From the error logs, it seems like you are trying to build for macOS. Does the issue still occur when you switch to iOS, as shown in the picture?

@CtrlJone 

<img width="867" alt="2024-08-16_12-36-50" src="https://github.com/user-attachments/assets/c4f74980-9585-4c3d-96a6-a5556ac66736">

<img width="611" alt="2024-08-16_12-38-24" src="https://github.com/user-attachments/assets/1f23f766-6aaf-46ff-8220-44c19e825506">
