### ISSUE TITLE
use grow() to fill space without overflowing

### ISSUE THREAD

**Issue by rgdev** [layoutBox/FlexLayout#37]
Hi,

I'm trying to make a simple view composed of one row of two columns : the first column contains two labels (title and subtitle below) and the second col contains a button with a static size and centered vertically.

My goal is to make the labels fill the remaining horizontal space to always have the button on the right side of the view. It works well when the text inside the labels is short and it's pushing the button outside the container once the text is long enough to cause the label to expand vertically.

What am I doing wrong ?

here's what i'm trying to achieve (green outline is the frame) : 

![schema](https://i.imgur.com/c3YnfA5.png)

here's the result on simulator : 

![schema](https://i.imgur.com/YQwmV8U.png)

here's the code : 

```
class MyView: BaseView {
    
    var titleLabel = UILabel()
    var subtitleLabel = UILabel()
    var infoButton = MyButton()
    var mainContainer = UIView()
    
    override init() {
        super.init()
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    fileprivate func setup() {
        subtitleLabel.numberOfLines = 0

        mainContainer.flex.direction(.row).define { (flex) in
            flex.addItem().grow(1).define({ (flex) in
                flex.addItem(titleLabel)
                flex.addItem(subtitleLabel).marginTop(Dimen.spacing.tiny)
            })
            flex.addItem().shrink(0).define({ (flex) in
                flex.addItem(infoButton).width(30).height(30).alignSelf(.center)
            })
        }
        
        addSubview(mainContainer)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        mainContainer.flex.layout()
    }
}
```

you can assume `BaseView` is a regular `UIView` and `Dimen.spacing.tiny` is just a CGFloat constant

**Comment by lucdion** [comment]
Hi @rgdev, you were almost there, the major issue was that the column container around your infoButton wasn't necessary. Also I've updated the line `mainContainer.flex.layout(mode: .adjustHeight)` so that the mainContainer height will be adjusted to match its content, but this may not be your desire.

Here is the updated class:
```
class MyView: BaseView {
    
    var titleLabel = UILabel()
    var subtitleLabel = UILabel()
    var infoButton = UIButton()
    var mainContainer = UIView()
    
    override init() {
        super.init()
        
        mainContainer.layer.borderColor = UIColor.green.cgColor
        mainContainer.layer.borderWidth = 1
        
        titleLabel.text = "titlelabel"
        titleLabel.textColor = .white
        titleLabel.textAlignment = .center
        titleLabel.backgroundColor = .red
        subtitleLabel.text = "subtitle label (long text causing wrapping)"
        subtitleLabel.textColor = .white
        subtitleLabel.textAlignment = .center
        subtitleLabel.numberOfLines = 0
        subtitleLabel.backgroundColor = .blue
        
        infoButton.setTitle("btn", for: UIControlState.normal)
        infoButton.titleLabel?.font = UIFont.systemFont(ofSize: 20)
        infoButton.backgroundColor = .cyan
        
        setup()
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        setup()
    }
    
    fileprivate func setup() {
        
        mainContainer.flex.direction(.row).define { (flex) in
            flex.addItem().grow(1).shrink(1).define({ (flex) in
                flex.addItem(titleLabel)
                flex.addItem(subtitleLabel).marginTop(10)
            })
            
            flex.addItem(infoButton).width(30).height(30).alignSelf(.center).marginLeft(5)
        }
        
        addSubview(mainContainer)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        
        mainContainer.pin.top().left().width(70%).margin(safeArea)
        mainContainer.flex.layout(mode: .adjustHeight)
    }
}
```

Results:
![simulator screen shot - iphone 8 plus - 2017-11-14 at 19 26 09 copy_800](https://user-images.githubusercontent.com/14981341/32812298-42060dc6-c972-11e7-9c37-e2094d6744bf.png)

![simulator screen shot - iphone 8 plus - 2017-11-14 at 19 26 37 copy_800](https://user-images.githubusercontent.com/14981341/32812299-421800da-c972-11e7-916a-c702302aa09e.png)

**Comment by rgdev** [comment]
Thank you !

Can you tell me why wrapping the button in a col container is causing this issue ?

**Comment by lucdion** [comment]
@rgdev you could keep it too, even if its not necessary, but you must apply the `.alignSelf(.center)` to this container:
```
mainContainer.flex.direction(.row).define { (flex) in
            flex.addItem().grow(1).shrink(1).define({ (flex) in
                flex.addItem(titleLabel)
                flex.addItem(subtitleLabel).marginTop(10)
            })
            
            flex.addItem().shrink(0).alignSelf(.center).define({ (flex) in
                flex.addItem(infoButton).width(30).height(30).marginLeft(5)
            })
        }
``` 

Result: 

![simulator screen shot - iphone 8 plus - 2017-11-15 at 08 57 47 copy_800](https://user-images.githubusercontent.com/14981341/32839655-1beaddc6-c9e3-11e7-96ce-f2bdeccd2f0f.png)

**Comment by rgdev** [comment]
That's perfect. thank you again :)
