### ISSUE TITLE
Combining FlexLayout & PinLayout - Check

### ISSUE THREAD

**Issue by egenvall** [layoutBox/FlexLayout#43]
Hi, I decided to try FlexLayout / PinLayout and have some questions about combining them and the workflow of "layers" and nested views.

Below is a super ugly sketch of the desired outcome:
![export](https://user-images.githubusercontent.com/3669105/33383550-efbf2b02-d523-11e7-9e3f-b190715c1a7c.png)

It's a UITableViewCell containing:
- One container (red): Which holds the row containing:
    - One circular UIView: (white) with green border
        - The circular UIView holds an UIImageView
    - One multi line label that scales

- Two lines (Green): From the top of the cell (no margin) to the top of the circular container and from the bottom of the cell to the bottom of the circular container

This was my approach after some mixing, checking your UITableView sample:
FlexLayout:
- Add a container with margin or padding, holding the row of items
- First item in row, add a rounded UIView with padding and call addItem on it to add the imageview within
- Add the multi line label to the container

Pin:
Add two UIViews and pin one to top, topCenter of the imageContainer while pinning the other one to bottom and bottomCenter of the imageContainer

(The red container is in reality transparent)

    fileprivate let iconImageView = UIImageView()
    fileprivate let nameLabel = UILabel()
    fileprivate let imageContainer = UIView()
    fileprivate let topLine = UIView()
    fileprivate let bottomLine = UIView()
    fileprivate let containerView = UIView()
    let padding: CGFloat = 16
    
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        selectionStyle = .none
        separatorInset = .zero
        iconImageView.contentMode = .scaleAspectFit
        contentView.backgroundColor = .white
        containerView.backgroundColor = .clear
        nameLabel.font = .getFont()
        nameLabel.numberOfLines = 0
        designLines()
        addLines()
        containerView.flex.define { (flex) in
            flex.addItem().direction(.row).padding(padding).define({ (flex) in
            flex.addItem(imageContainer).size(40).alignSelf(.center).padding(5)
                .addItem(iconImageView).size(30).aspectRatio(1)
                flex.addItem(nameLabel).marginLeft(padding).grow(1).shrink(1)
            })
        }
        addSubview(containerView)
    }
    private func addLines() {
        contentView.addSubview(topLine)
        contentView.addSubview(bottomLine)
    }
    private func designLines() {
        topLine.backgroundColor = .green
        bottomLine.backgroundColor = .green
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    func configure(_ text: String) {
        nameLabel.text = text
        nameLabel.flex.markDirty()
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        imageContainer.setupCircleView(backgroundColor: .white, borderThickness: 2.0, borderColor: .green)
        contentView.flex.layout(mode: .adjustHeight)
    }
    
    // MARK: - Pin the lines to top / bottom of the cell and centered by imageContainer
    private func pinLines() {
        topLine.pin.top().bottomCenter(to: imageContainer.anchor.topCenter).width(2)
        bottomLine.pin.bottom().topCenter(to: imageContainer.anchor.bottomCenter).width(2)
    }
    
    fileprivate func layout(_ size: CGSize) {
        containerView.pin.width(size.width)
        containerView.flex.layout(mode: .adjustHeight)
        pinLines()
    }
    
    override func sizeThatFits(_ size: CGSize) -> CGSize {
        layout(size)
        return containerView.frame.size
    }
}

Ideally I'd go with margin on the containerView but it ended up wonky, and right now the bottom green line isn't showing.

Is this a sane approach to layout this type of view or do you have a better suggestion?

Best,

**Comment by lucdion** [comment]
Hi @egenvall, you were almost there! Great work. The only thing missing is a call to `pinLines()`in layoutSubViews:

```
    override func layoutSubviews() {
        super.layoutSubviews()
        
        imageContainer.backgroundColor = .white
        imageContainer.layer.borderColor = UIColor.green.cgColor
        imageContainer.layer.borderWidth = 2
        contentView.flex.layout(mode: .adjustHeight)
        
        pinLines()
    }
```

Also, another solution would be to use only FlexLayout, here is an updated version:
```
   override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        selectionStyle = .none
        separatorInset = .zero
        iconImageView.contentMode = .scaleAspectFit
        contentView.backgroundColor = .white
        containerView.backgroundColor = .clear
//        nameLabel.font = .getFont()
        nameLabel.numberOfLines = 0
        designLines()
        
        containerView.flex.direction(.row).alignItems(.stretch).paddingHorizontal(padding).define({ (flex) in
            flex.addItem().alignItems(.center).define({ (flex) in
                flex.addItem(topLine).width(2).height(padding)
                flex.addItem(imageContainer).size(40).padding(5)
                    .addItem(iconImageView).size(30).aspectRatio(1)
                flex.addItem(bottomLine).width(2).height(padding)
            })
            
            flex.addItem(nameLabel).marginLeft(padding).grow(1).shrink(1)
        })
        
        contentView.addSubview(containerView)
    }

    private func designLines() {
        topLine.backgroundColor = .green
        bottomLine.backgroundColor = .green
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    func configure(_ text: String) {
        nameLabel.text = text
        nameLabel.flex.markDirty()
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        
        imageContainer.backgroundColor = .white
        imageContainer.layer.borderColor = UIColor.green.cgColor
        imageContainer.layer.borderWidth = 2
        imageContainer.layer.cornerRadius = imageContainer.frame.width / 2
        contentView.flex.layout(mode: .adjustHeight)
    }

    fileprivate func layout(_ size: CGSize) {
        containerView.pin.width(size.width)
        containerView.flex.layout(mode: .adjustHeight)
    }
    
    override func sizeThatFits(_ size: CGSize) -> CGSize {
        layout(size)
        return containerView.frame.size
    }
```

Here is the result 
![simulator screen shot - iphone 8 plus - 2017-11-29 at 11 53 44](https://user-images.githubusercontent.com/14981341/33387766-2511be82-d4fc-11e7-870f-84dc837073f3.png)

Note that sometimes FlexLayout setup requires some thinking. But there are often multiple solutions.

luc

**Comment by egenvall** [comment]
Thank you for your swift reply! (pun intended)

Ah, so close. 
Thank you for the help and the alternative solution, really helps to get into the way of thinking around FlexLayout.

Best, Kim
