### ISSUE TITLE
Adding Dynamic Content to UITableViewCell

### ISSUE THREAD

**Issue by egenvall** [layoutBox/FlexLayout#44]
Hi again.

I'm trying to update my UITableViewCell with a dynamic number of views after it has been fetched from the database. The layout works fine (I love it) when I run it with fixed content that is available when the cell is initiated.

Basically I retrieve some tasks, and reload the table, calling configure(_ ...) with the data in the cellForRow
Other code omitted for simplicity

```
fileprivate var tasks: [SomeRandomObject] = []
private func setupFlexContainer() {
        contentView.flex.define { flex in
            // Green Container
            flex.addItem(titleContainer)
                .padding(padding)
                .alignItems(.stretch)
                .backgroundColor(.green)
                .define { flexTitleContainer in
                    flexTitleContainer.addItem(exerciseLabel)
                    flexTitleContainer.addItem(exerciseName).marginTop(8).grow(1).shrink(1)
                }
            // Exercise row
                for task in tasks {
                    flex.addItem()
                        .direction(.row)
                        .padding(padding)
                        .define { nameRow in
                            nameRow.addItem(generateIcon(for: task)).size(30).aspectRatio(1)
                            nameRow.addItem(generateLabel(for: task)).grow(1).marginLeft(16)
                        }
                }

            flex.addItem(acceptButton)
                .backgroundColor(.red)
                .height(50)
                .marginHorizontal(padding)
            
            flex.addItem(descriptionLabel)
                .alignSelf(.center)
                .marginBottom(padding)
                .marginTop(8)
        }
    }

func configure(_ exerciseTasks: [SomeRandomObject]) {
        tasks = exerciseTasks
        contentView.flex.markDirty()
        setNeedsLayout()
 }
    
override func layoutSubviews() {
        super.layoutSubviews()
        layout()
 }
    
fileprivate func layout() {
        contentView.flex.layout(mode: .adjustHeight)
}
    
override func sizeThatFits(_ size: CGSize) -> CGSize {
        contentView.pin.width(size.width)
        layout()
        return contentView.frame.size
}

``` 

However, I can't get view to relayout when the *tasks* has been filled with objects

Any help is appreciated.

Best,

**Comment by lucdion** [comment]
Hi @egenvall, in your `configure` method you must remove all previously added **Exercise row** and then add the new list of tasks. Calling `flex.addItem()` adds a subview to the container. You must then clear all previous exercise rows.

I see two easy way of doing this:
1. **Simple method**: Remove all contentView's subviews (`contentView.subviews.forEach({ $0.removeFromSuperview})`) and then call your `setupFlexContainer()` method.

2. **More efficient method**: Add a column exercises container in `setupFlexContainer()` that will contain all your exercise rows. Then in the configure remove all the exercises container's subviews and add new exercise rows.

**Comment by egenvall** [comment]
Yes you are right, such a silly mistake. Thanks for the clarification, and great work on FlexLayout, absolutely love it so far!
