### ISSUE TITLE
Updating a label value results in truncated text even after updating layout

### ISSUE THREAD

**Issue by rgdev** [layoutBox/FlexLayout#45]
Hello, I noticed something while building a layout : when a label's text value is updated its bounds don't seem to update even after layoutSubviews is executed in the parent view.

Here's a simple example : I have a controller with a flex container containing a button and a label. Pressing the button assign a new text to the label (a bit longer than the original value) and setNeedLayout is called on the controller's view. However doing so cause the UILabel to truncate the text.

```
class DummyView: UIView {
    
    let flexContainer = UIView()
    let button = UIButton()
    let label = UILabel()
    
    required init?(coder aDecoder: NSCoder) { super.init(coder: aDecoder) }
    override init(frame: CGRect) { super.init(frame: frame) }
    
    convenience init() {
        self.init(frame: .zero)
        self.button.setTitle("button", for: .normal)
        self.button.setTitleColor(UIColor.red, for: .normal)
        self.label.text = "hello"
        
        flexContainer.flex.padding(20).alignItems(.center).define { (flex) in
            flex.addItem(button).width(100%)
            flex.addItem(label).marginTop(10)
        }
        addSubview(flexContainer)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        self.flexContainer.pin.top().left().right()
        self.flexContainer.flex.layout(mode: .adjustHeight)
    }
    
}
```

```
class DummyController: UIViewController {

    fileprivate var mainView: DummyView { return self.view as! DummyView }
    init() {  super.init(nibName: nil, bundle: nil) }
    required init?(coder aDecoder: NSCoder) { super.init(coder: aDecoder) }
    override func loadView() { view = DummyView() }
    
    override func viewDidLoad() {
        super.viewDidLoad()
        mainView.button.addTarget(self, action: #selector(onButtonPressed(sender:)), for: .touchUpInside)
    }
    
    @objc func onButtonPressed(sender: UIButton) {
        mainView.label.text = "goodbye"
        mainView.setNeedsLayout()
    }
    
}
```

![before](https://i.imgur.com/QKy8Zyh.png)

![after](https://i.imgur.com/0NU2DMZ.png)

**Comment by lucdion** [comment]
Hi @rgdev, items are re-layouted only when their container size change or when an item's flex property is modified. For any other changes, you must call `markDirty()` to force a re-layout.

See https://github.com/layoutBox/FlexLayout#markdirty for more details.

In your case you need:
```
   @objc func onButtonPressed(sender: UIButton) {
        mainView.label.text = "goodbye"
        mainView.label.flex.markDirty()
        mainView.setNeedsLayout()
    }
```

**Comment by rgdev** [comment]
Such a silly mistake, thank you for the swift answer!
Do you think it would be possible to have UILabels to automatically mark themselves as dirty when their text field is updated in a futur version ?

**Comment by lucdion** [comment]
@rgdev you can do that easily by subclassing the UILabel class (ex: Label / FlexLabel) and override the `text` property setter.

You can also add an UILabel extension and add a property OR a method for setting the text that would call `markDirty()`. 
ex:
```
extension UILabel {
       // Property
       var flexText: String? {
        get {
            return self.text
        }
        set {
            self.text = newValue
            self.flex.markDirty()
        }
    }

    // Method
    func updateText(_ text: String) {
        self.text = text
        flex.markDirty()
    }
}
```

**Comment by rgdev** [comment]
Thank you @lucdion, I was actually wondering if you think such extension would be worth adding to FlexLayout directly.

**Comment by lucdion** [comment]
I prefer not to add extension to base UIKit classes. There is always the possibility of name clashes with app' extensions.

I could add a subclass of UILabel, but I need to think about that.
Thanks for your input!
