### ISSUE TITLE
Preprocessor macros

### ISSUE THREAD

**Issue by Rag0n** [layoutBox/FlexLayout#50]
Hi!

I have an issue with preprocessor macros, such as FLEXLAYOUT_USE_CARTHAGE. There is situations when I cannot set them, eg: in swift playgrounds. 

I just removed them and everything works fine. But I have a question why you are using them at all? I mean what are the cases when we need to import Yoga instead of YogaKit?

I think those preprocessor macros should be removed. Or maybe you should revert them: without macros we should import YogaKit, with macro should import Yoga. Because it seems like YogaKit import is used in almost every case.

Thank you! 

P.S. I can send a pull request if you wish.

**Comment by lucdion** [comment]
Hi @Rag0n you're welcome to submit a PR 👍

**Comment by lucdion** [comment]
Hi @Rag0n, we must use `Yoga` when using pods instead of carthage, because yoga's pod is named `Yoga` and not `YogaKit`. Supporting both package manager wasn't easy since we don't control yoga.

**Comment by Rag0n** [comment]
@lucdion 
Thank you, I dived into source code a little bit yesterday and understood it. I was thinking about renaming YogaKit into Yoga because we are using forked version of Yoga anyway to add carthage support.

**Comment by lucdion** [comment]
Yes, we could rename YogaKit, but I thought it was preferable to limit as much as possible the number of changes to the yoga's fork.

**Comment by Rag0n** [comment]
I don't think its a big change. I mean in fork you have created separate xcodeproj to add support for Carthage and to rename framework we just need to rename target's name. Maybe I'm wrong, but seems like it is not a big change.

**Comment by Rag0n** [comment]
Seems like that issue is solved and can be closed because of last changes.
