### ISSUE TITLE
Shrink and Expand the UIView with its child UIView components shrinking as well through PanGesture.

### ISSUE THREAD

**Issue by yashbedi** [layoutBox/FlexLayout#55]
Hey hie thanks for the Awesome Library =D .

So there's a small problem which I'm facing
I was able to add a pan gesture in the View which is inherited from BaseView in ViewController inherited from BAseViewController . (Followed the same approach which is in the Example code of the library swift).

The below gif shows my requirements.
This thing is done from storyboard I'm trying it using FlexLayout.

So here(in the gif) I added the priorities to UIVIew with Autolayout then made an IBoutlet of NSLayoutConstraint 
so when I swipe up using PAN gesture the view Expands and while sliding down the view shrinks (so as the constraints.constant value). So all the sliding up and down is done on that Iboutlet of NSLayoutConstraint.constant value (I mean I modify the value so the view changes its height with  :usingSpringWithDamping  effect)

![imageedit_3_3530390270](https://user-images.githubusercontent.com/3687481/35549343-152ec746-05ab-11e8-95fc-8d56c9d6afab.gif)

But in FlexLayout I Couldn't get the constraints.constant value . I know FlexLayout lays out the view.. but How to achieve the above scenario with FlexLayout.

Looking for immediate help.
Thanks =)

[P.S. Sorry for hiding the details, there are some copyright thingy issues.]

**Comment by lucdion** [comment]
Hi @yashbedi,

It's difficult to answer your question without having the full example, if you can share it your FlexLayout test, I could answer you correctly. 

Currently you probably have something like that:
```
UIView.animate(withDuration: animated ? duration : 0) {
     myConstraint.constant = isExpanded ? 100 : 20
     view.layoutIfNeeded() 
}
```

Changing that to FlexLayout would be similar:
```
UIView.animate(withDuration: animated ? duration : 0) {
     myView.flex.height(isExpanded ? 100 : 20)
     myView.flex.markDirty() // may not be needed in your case
     // Relayout the flex container embedding your view. See https://github.com/layoutBox/FlexLayout#layout
     myFlexContainer.flex.layout()
}
```

If you share me your example, I'll be able to check it.

luc

**Comment by yashbedi** [comment]
Its working with the solution you gave. I got it. Thanks 
you can close the issue =).
