### ISSUE TITLE
tvOS support and Podspec

### ISSUE THREAD

**Issue by johankool** [layoutBox/FlexLayout#56]
I did see some references to tvOS in the code, but the Podspec doesn't declare its support for tvOS. Is this omission on purpose? Not being ready for tvOS for example?

**Comment by lucdion** [comment]
Hi @johankool, it is planned but not implemented yet.

**Comment by lucdion** [comment]
I have no plan to support that, I don't have enough time to do that, so I'll close this issue. Sorry.
