### ISSUE TITLE
UILabel size is not enough to render the text

### ISSUE THREAD

**Issue by wjling** [layoutBox/FlexLayout#58]
I have a tableView and three cells. Each cell has two labels: `timeLabel` and `titleLabel`. The first two titleLabels, whose background colors are red,  have the same text "未命名". The first one show full text, but the second one not.
My code in the cell:
```
self.contentView.flex.direction(.row).define { (flex) in
    flex.addItem(timeLabel)
    flex.addItem(titleLabel).marginLeft(10).shrink(1).backgroundColor(UIColor.red)
}
```
![image](https://user-images.githubusercontent.com/4201777/36060676-ed83cfde-0e88-11e8-87f7-cf412311697d.png)

**Comment by lucdion** [comment]
Hi @wjling, its difficult to tell you your issue, but one possible reason is that after setting the titleLabel you don't call `titleLabel.flex.markDirty()`, and then you may have to force a relation of the flex container by call your cells's `setNeedsLayout`.

**Comment by wjling** [comment]
I have called `titleLabel.flex.markDirty()`. Maybe there is something to do with Chinese characters. I guess the first titleLabel and the second are of the same width, but the second one just not render the text correctly. What I can do is to add extra point to the label by using `paddingRight(0.5)` to give the label enough space to render the text, and it works as desired

**Comment by linqingmo** [comment]
```swift
private class Cell: UITableViewCell {
    let timeLabel = UILabel()
    let titleLabel = UILabel()
            
    override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        contentView.flex.direction(.row).define { flex in
            flex.addItem(timeLabel)
            flex.addItem(titleLabel).marginLeft(10).shrink(1).backgroundColor(.red)
        }
    }
            
    required init?(coder aDecoder: NSCoder) {
         fatalError("init(coder:) has not been implemented")
    }
            
    override func layoutSubviews() {
         super.layoutSubviews()
         contentView.flex.layout()
     }
}
```
How do you layout your cell? It works fine for me.
<img width="341" alt="2018-03-16 5 19 41" src="https://user-images.githubusercontent.com/7324811/37512885-4b799720-293e-11e8-9e31-22e9a4fe51fc.png">

**Comment by wjling** [comment]
```
override init(style: UITableViewCellStyle, reuseIdentifier: String?) {
        super.init(style: style, reuseIdentifier: reuseIdentifier)
        configureViews()
    }

private func configureViews() {
        self.backgroundColor = UIColor.clear
        
        self.selectedBackgroundView = UIView()
        
        timeLabel.font = UIFont.systemFont(ofSize: 13)
        timeLabel.textColor = UIColor.white
        titleLabel.font = UIFont.systemFont(ofSize: 13)
        titleLabel.textColor = KLColor.gray_FAFAFA
        self.contentView.flex.direction(.row).define { (flex) in
            flex.addItem(timeLabel)
            flex.addItem(titleLabel).paddingEnd(0.5).marginLeft(10).shrink(1)
        }
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        layoutMyViews()
    }
    
    func layoutMyViews() {
        self.contentView.flex.layout()
    }
```
My code like above, seems almost the same with yours @linqingmo. I add `paddingEnd(0.5)` to make sure there is enough room to render the text

**Comment by lucdion** [comment]
No recent activities => closing this discussion.
