### ISSUE TITLE
Need some help about layout wrap

### ISSUE THREAD

**Issue by darkhandz** [layoutBox/FlexLayout#73]
I'm new to use FlexLayout, and I want to layout 2~9 imageViews (aspectRatio 1:1) like this:
![image](https://user-images.githubusercontent.com/2143333/37914849-c31d3bce-314a-11e8-91a6-7cfe1bf890b9.png)

But I try my best, not really exact:
![image](https://user-images.githubusercontent.com/2143333/37914597-2a6f713a-314a-11e8-99f0-37e6347af031.png)

 My code is here, hope you can give me some solution😆 :

```swift
import UIKit
import FlexLayout
import PinLayout

class TestView: UIView {
    fileprivate let rootFlexContainer = UIView()
    
    init() {
        super.init(frame: .zero)
        backgroundColor = .white
        rootFlexContainer.backgroundColor = .yellow
        addSubview(rootFlexContainer)
        
        var picViews = [UIImageView]()
        for _ in 0..<9 {
            let imageView = UIImageView(image: UIImage(named: "method"))
            imageView.contentMode = .scaleAspectFill
            imageView.clipsToBounds = true
            picViews.append(imageView)
            rootFlexContainer.addSubview(imageView)
        }
        
        rootFlexContainer.flex.direction(.row).wrap(.wrap)
            .marginLeft(50).marginTop(100).define { flex in
            for (i, imgV) in picViews.enumerated() {
                flex.addItem(imgV).width(30%).aspectRatio(1)
                if i % 3 > 0 { // 右2列
                    imgV.flex.marginLeft(10)
                }
                if i / 3 > 0 { // 下2行
                    imgV.flex.marginTop(10)
                }
            }
        }
    }
    
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        rootFlexContainer.pin.top().horizontally().width(87%)
        rootFlexContainer.flex.layout(mode: .adjustHeight)
    }
}
```

**Comment by lucdion** [comment]
Hi @darkhandz, maybe just be enabling items to grow and don't limit them to a width of 30% would fill the right empty space.

Note that I haven't tested this code

```
init() {
    rootFlexContainer.flex.direction(.row).wrap(.wrap).define { flex in
            for (i, imgV) in picViews.enumerated() {
                flex.addItem(imgV).minWidth(30%).aspectRatio(1).grow(1)

                if i % 3 > 0 { // 右2列
                    imgV.flex.marginLeft(10)
                }
                if i / 3 > 0 { // 下2行
                    imgV.flex.marginTop(10)
                }
            }
        }
} 

override func layoutSubviews() {
        super.layoutSubviews()
        rootFlexContainer.pin.top(100).hCenter().width(87%)
        rootFlexContainer.flex.layout(mode: .adjustHeight)
}
```

**Comment by darkhandz** [comment]
@lucdion Thanks for you reply. 

I've try the code above, `minWidth(30%)` doesn't work as expect:
![image](https://user-images.githubusercontent.com/2143333/38002927-a486e566-3267-11e8-8b7d-76407aa9679d.png)

but `width(30%)` does:
![image](https://user-images.githubusercontent.com/2143333/38002942-bfa6359a-3267-11e8-8211-f82449670b6b.png)

And, when `picViews`'s elements reduce to 8...
![image](https://user-images.githubusercontent.com/2143333/38002995-02287aea-3268-11e8-993a-2a9a4c5f74db.png)

I think I have to calculate the accurate width for the `imgV` `(rootFlexContainer.width - margin * (column - 1) / column)`

**Comment by lucdion** [comment]
Using `width(30%)` it really does that https://user-images.githubusercontent.com/2143333/38002995-02287aea-3268-11e8-993a-2a9a4c5f74db.png?

**Comment by darkhandz** [comment]
@lucdion Yes...All my code is shown below.

![image](https://user-images.githubusercontent.com/2143333/38039369-b35c4b76-32df-11e8-931a-b02fdb3d7da9.png)

**Comment by lucdion** [comment]
I'm surprised that flexbox's `width` property priority is not higher. And what if you add `maxWidth(30%)`?

**Comment by darkhandz** [comment]
@lucdion I replace `width(30%)` with `maxWidth(30%)`, now it looks like this:

![image](https://user-images.githubusercontent.com/2143333/38064032-aab1f56c-332e-11e8-9cbc-59fd7f82993e.png)

**Comment by lucdion** [comment]
@darkhandz then I think that a solution that could work would be to create multiple row containers containing 3 images each. This way you wouldn't have the right margin on each row.
