### ISSUE TITLE
Button size seems to be larger than intrinsic size

### ISSUE THREAD

**Issue by wjling** [layoutBox/FlexLayout#75]
I have a `view` with a `containerView`. There are two `UILabel`s and a `UIButton` added to `containerView`, named `titleLabel0` with text "000000...",  `titleLabel1` with text "1111111...", `button0` with text "222222...". Layout is shown in image below. I wonder why the button0's size is not the same as its titleLabel's ?
![image](https://user-images.githubusercontent.com/4201777/38533006-da3cd5b6-3ca9-11e8-8357-9d6426b74225.png)

In addition, my layout code is:
```
self.addSubview(containerView)
self.containerView.flex.direction(.column).alignItems(.center).define { (flex) in
        flex.addItem(tipLabel0)
        flex.addItem(tipLabel1).marginTop(10)
        flex.addItem(button0).marginTop(40)
}
```

```
override func layoutSubviews() {
        super.layoutSubviews()
        self.containerView.pin.width(100%)
        self.containerView.flex.layout(mode: .adjustHeight)
}
```

**Comment by linqingmo** [comment]
It's nothing to do with FlexLayout. It's because `button.sizeThatFits(size) is larger than button.titleLabel?.sizeThatFits(size)`

**Comment by wjling** [comment]
OK, I see. Thank you for your help. @linqingmo
