### ISSUE TITLE
Update license to MIT

### ISSUE THREAD

**Issue by tsafrir** [layoutBox/FlexLayout#76]
Following the recent update of Yoga license to MIT shouldn't FlexLayout update the license of FlexLayout and PinLayout to MIT also.
It will be very much appreciated.

**Comment by lucdion** [comment]
Hi @tsafrir, what are the major differences between MIT and BSD 3-Clause "New"?

**Comment by tsafrir** [comment]
Hi @lucdion, I asked since I thought it may be a problem to use FlexLayout in a close-source commercial SDK. 
From what I just found it maybe ok (although I guess I'll forward that to a lawyer anyway). 
But generally speaking, if you choose a MIT license, it's a simple and permissive license (which also match Yoga). While BSD is a confusing license because all it's other flavors.

**Comment by lucdion** [comment]
Ok, I'll change that, I don't have any issue with using the MIT license.

**Comment by tsafrir** [comment]
Thanks a lot!

**Comment by lucdion** [comment]
Done! 
PinLayout will be updated soon.

**Comment by tsafrir** [comment]
Hey @lucdion thanks for the updating FlexLayout to MIT license.
I noticed that the Podspec license field  also need to be updated.
thanks again

**Comment by lucdion** [comment]
Done @tsafrir 🙂
