### ISSUE TITLE
Need help for text UILabel and setCollectionViewLayout(newLayout, animated: true)

### ISSUE THREAD

**Issue by sLm-s** [layoutBox/FlexLayout#80]
Hi @lucdion . How to compress the text if it does not fit in frames box? For example, decrease the font size.
label.adjustsFontSizeToFitWidth = true and  label.adjustsFontForContentSizeCategory = true - not work

<img width="237" alt="2018-04-18 12 02 54" src="https://user-images.githubusercontent.com/20534572/38914365-e8d717a0-4300-11e8-927a-841976096f16.png">
<img width="233" alt="2018-04-18 12 03 20" src="https://user-images.githubusercontent.com/20534572/38914366-e8fb3356-4300-11e8-91b7-3530289edad4.png">

And if you do not mind, how to change the display of objects in cells if the cell size has changed. For example, a grid has become a table.

<img width="246" alt="2018-04-18 12 13 12" src="https://user-images.githubusercontent.com/20534572/38914683-4381a66a-4302-11e8-8a8d-19bc0e9c6148.png">
<img width="443" alt="2018-04-18 12 13 29" src="https://user-images.githubusercontent.com/20534572/38914684-43a2c700-4302-11e8-93b5-446c4da6e77b.png">

**Comment by lucdion** [comment]
@sLm-s, sorry not sure to understand your first question. You seems to have a question regarding a UILabel's font size, but your arrows are pointing a gray line. Could you give me more details?

For your second question, I see two choices:
1. remove all subviews and rebuild everything using new containers and items.
2. Update all your views flex's properties to match the other design.

**Comment by sLm-s** [comment]
At the top of the cell, the text does not fit into the specified area and the bottom is all normal. The question of how to reduce the font, if the text does not fall within the specified scope.

<img width="570" alt="2018-05-02 9 36 43" src="https://user-images.githubusercontent.com/20534572/39504512-e947ecb2-4ded-11e8-9055-9058116b24e3.png">

**Comment by sLm-s** [comment]
Thanks, I understood how the problem can be solved. The topic can be closed. )
