### ISSUE TITLE
about marginTop(n%) not refer to superView's height

### ISSUE THREAD

**Issue by darkhandz** [layoutBox/FlexLayout#81]
My code is:

```swift
import UIKit
import FlexLayout

class YogaExampleAView: BaseView {
    fileprivate let rootFlexContainer = UIView()

    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
    }
    
    override init() {
        super.init()
        rootFlexContainer.flex.define { (flex) in
            flex.addItem().width(80).height(40).marginLeft(20).marginTop(10%).backgroundColor(.blue)
            flex.addItem().height(100).width(250).marginLeft(40).marginTop(20).backgroundColor(.green).define { flex in
                flex.addItem().height(20).width(30).marginTop(16%).backgroundColor(.magenta)
            }
        }
        addSubview(rootFlexContainer)
    }
    
    override func layoutSubviews() {
        super.layoutSubviews()
        rootFlexContainer.frame = bounds
        rootFlexContainer.flex.layout()
    }
}
```
the UI looks like :

![image](https://user-images.githubusercontent.com/2143333/39002975-62fa6754-442c-11e8-8d2c-85c3380600b0.png)

As you see, I set the blue view's marginTop to 10% (I assume that means 10% height of it's superView), but the blue view's Y is actually 37.5, by a strange coincidence, It's 10% of the superView's width(375).

And then, I verify with magenta view's width and Y:

![image](https://user-images.githubusercontent.com/2143333/39003426-6b6a08d0-442d-11e8-8de7-3ebdbb400735.png)

The magenta view's Y is 40, 16% of the superView's(green) width(250).

Just confuse about that...😳

**Comment by lucdion** [comment]
Hi @darkhandz, you're right, Yoga as implemented top/bottom percentages handling as CSS does, i.e. it use the container's width, not the container's height as we would have expected.

See CSS documentation here: https://www.impressivewebs.com/vertical-percentages-css/
```
A percentage value on **top/bottom** padding or margins is **relative to the width of the containing block**
```

**Comment by darkhandz** [comment]
So……I am ignorant and ill-informed 😅, thanks for you explaining
