### ISSUE TITLE
No such module 'FlexLayout'

### ISSUE THREAD

**Issue by Martian2Lee** [layoutBox/FlexLayout#90]
`git clone https://github.com/layoutBox/FlexLayout.git`
`cd FlexLayout/Example/`
`pod install`
![image](https://user-images.githubusercontent.com/22679825/39967280-ad5dadb0-56c9-11e8-9afd-fb593b36cf53.png)
![image](https://user-images.githubusercontent.com/22679825/39967283-b2156e24-56c9-11e8-8439-fc91c33b98cf.png)

**Comment by el-hoshino** [comment]
Probably you need to open FlexLayout.xcworkspace instead of Example/FlexLayoutSample.xcodeproj, and run the example target inside the workspace

**Comment by Martian2Lee** [comment]
Got it thank you @el-hoshino !
