### ISSUE TITLE
How to use baseline alignment?

### ISSUE THREAD

**Issue by darkhandz** [layoutBox/FlexLayout#91]
Hi Luc,
I don't know how to use the `baseline` alignment, they seems like not working as expect:

![image](https://user-images.githubusercontent.com/2143333/40429387-2e9eb62c-5ed5-11e8-8bff-b7bbac4450b9.png)

my code is here:

```swift
import UIKit
import FlexLayout

class ViewController: UIViewController {
    
    override func viewDidLoad() {
        super.viewDidLoad()
        setupSubviews()
    }

    fileprivate func setupSubviews() {
        let label1 = UILabel()
        label1.text = "Hello."
        label1.font = UIFont.systemFont(ofSize: 18)
        
        let label2 = UILabel()
        label2.text = ".world."
        label2.font = UIFont.systemFont(ofSize: 12)
        
        let label3 = UILabel()
        label3.text = ".Intro."
        label3.font = UIFont.systemFont(ofSize: 22)
        
        let label4 = UILabel()
        label4.numberOfLines = 0
        label4.text = ".controller"
        label4.font = UIFont.systemFont(ofSize: 30)
        
        view.flex.paddingTop(100).define{ flex in
            flex.addItem().direction(.row).alignItems(.baseline).backgroundColor(.green).define{ flex in
                flex.addItem(label1).backgroundColor(.red)
                flex.addItem(label2).backgroundColor(.yellow)
                flex.addItem(label3).backgroundColor(.magenta)
                flex.addItem(label4).backgroundColor(.cyan)
            }
        }
        
    }    
   
    override func viewDidLayoutSubviews() {
        super.viewDidLayoutSubviews()
        view.flex.layout()
    }
}
```

**Comment by lucdion** [comment]
Sorry @darkhandz, I have never used the baseline alignment 😕  And as I did find out, it looks like it's not even supported by Yoga current implementation.

Here are few links related to ReactNative:
* https://react-native.canny.io/feature-requests/p/support-for-baseline-alignment
* https://reactnativecode.com/apply-alignitems-on-view-explained/

I think we should remove the support of `baseline` until it is supported.

Anyone tried to use baseline?

**Comment by darkhandz** [comment]
What a pity! So, we have to hardcode the labels margin to achieve that.

P.S. Why README.MD write `8. Borders`, but I can't find the related methods.😆
