### ISSUE TITLE
What am I do wrong?

### ISSUE THREAD

**Issue by dillidon** [layoutBox/FlexLayout#92]
![1](https://user-images.githubusercontent.com/7115804/40443568-695730ec-5ecf-11e8-8c66-bf7cf2189ad2.png)

``` swift

textView.flex.direction(.column).padding(UI.Cards.inset).justifyContent(.center).define { flex in
    
  flex.addItem(section)   
  flex.addItem().direction(.rowReverse).position(.absolute).left(UI.Cards.inset).bottom(UI.Cards.inset).right(UI.Cards.inset).justifyContent(.spaceBetween).define { flex in
    
    flex.addItem(button).height(28).maxWidth(50%).grow(1).position(.absolute).right(0).bottom(0)
    flex.addItem().direction(.column).define {

       flex.addItem(title).shrink(1)
       flex.addItem(subtitle).shrink(1)
    }
  }
}
```

**Comment by egenvall** [comment]
One way to do it is to have two containers.
Container A is containing Container B & Your Button
Container B is containing your labels.

Just make some modifications to the grow, shrink & sizing depending on your needs and it should work. (Didn't try it)
``` 
...
flex.addItem().direction(.row).alignItems(.center).alignSelf(.end).define { detailContainer in 
    detailContainer.addItem().marginRight(16).define { textContainer in
        // Grow, Shrink & Margin between these as you need
        textContainer.addItem(title)
        textContainer.addItem(subtitle)
    }
    detailContainer.addItem(button) // Size, Margin, etc this as you need
}

```

**Comment by dillidon** [comment]
@egenvall it doesnt work properly(

<img width="390" alt="2018-05-23 22 31 58" src="https://user-images.githubusercontent.com/7115804/40446837-3b4797fa-5ed9-11e8-82aa-4cae0b9c8b4e.png">

The button with price can be of different width depends on the price itself, so `maxWidth` that solves, but margin between 2 labels and button doesnt work if button set with `.position(.absolute).right(0)`...

Please, help)

**Comment by egenvall** [comment]
You should not place the button using .position(.absolute)
Sat down with Xcode now:

```
cardContainer.addItem().position(.absolute).left(16).right(16).bottom(16)             
.backgroundColor(.blue).direction(.row).justifyContent(.spaceBetween).alignItems(.center).define { detailContainer in
                    detailContainer.addItem().backgroundColor(.yellow).marginRight(16).grow(1).shrink(1).define { textContainer in
                        textContainer.addItem(titleLabel)
                        textContainer.addItem(subtitleLabel)
                    }
                    detailContainer.addItem(button).shrink(0)
                    
}
```

Result: https://webmshare.com/3XYVr

Now you probably won't change the button content at click, but this demonstrates the resizing. You could also fit the label size to fit the new width

**Comment by egenvall** [comment]
@lucdion @dillidon  Can close this issue

**Comment by dillidon** [comment]
@egenvall if you want, but the problem is not still solved. I tried all possible combinations and always one or two bugs is. I think you should rethink logiq of your framework.

**Comment by egenvall** [comment]
@dillidon I assumed that the issue could be closed after you replied to my solution.
What bugs are you experiencing?

**Comment by dillidon** [comment]
I've just solved this with PinLayout and didnt make a screenshot. Same amount of code with PinLayout. Your framework does not work correctly. Simple rules work fine, but when you need to do something a little more complicated, errors appear. Not only in this moment, but in others. Too many functions and it is not clear how they will act together. If you do it by intuition or by your instructions, then nothing happens with complicated situations. Close the topic.

**Comment by lucdion** [comment]
I agree with you @dillidon 🙂, in many situation PinLayout gives you the full control over your layout. And yes, there are few issues with Yoga's implementation of flexbox (https://github.com/facebook/yoga).
