### ISSUE TITLE
Xcode 10 Beta

### ISSUE THREAD

**Issue by sLm-s** [layoutBox/FlexLayout#96]
Hi @lucdion. I guess I'm rushing things but if you fix this mistake it would be good in Xcode 10 Beta

Error - Module compiled with Swift 4.1.2 cannot be imported in Swift 4.1.50:

**Comment by lucdion** [comment]
Have you tries to clean up everything, including derived-data? If you use carthage, you should also delete the carthage directory completely.

**Comment by sLm-s** [comment]
I just installed Xcode 10 beta and it gives me this error

**Comment by sLm-s** [comment]
@lucdion Hi. The question can be closed. I figured it out, I just had to update everything. Thank you for your time
