### ISSUE TITLE
The best way to do this

### ISSUE THREAD

**Issue by tribushevsky** [layoutBox/FlexLayout#97]
Hello! I need to make custom view that contains self sized UITextView. I need to change height for textView and "green view" when content for textView bigger than UITextView.contentView can contain. And I need to have a maximum height for textView or "green view".  What is the best way to do this?

Code from init method for "green view":

`
attachmentButton = UIButton()
        self.attachmentButton.setImage(UIImage.init(named: "ic_attachment"), for: UIControlState.normal)
        self.attachmentButton.pin.size(32)
        
        self.sendButton = UIButton()
        self.sendButton.setImage(UIImage.init(named: "ic_send"), for: UIControlState.normal)
        self.sendButton.pin.size(32)
        
        inputTextView = UITextView()
        inputTextView.delegate = self
        inputTextView.isScrollEnabled = false
        inputTextView.font = UIFont.systemFont(ofSize: 17)
        inputTextView.backgroundColor = UIColor.red
        
        self.flex.direction(.column).paddingTop(10).paddingBottom(10).define { (flex) in
            flex.addItem().direction(.row).define { (flex) in
                flex.addItem(self.attachmentButton).paddingLeft(10).paddingRight(10)
                flex.addItem(self.inputTextView).grow(1)
                flex.addItem(self.sendButton).paddingLeft(10).paddingRight(10)
            }
        }`

![screen shot 2018-06-07 at 16 16 17](https://user-images.githubusercontent.com/26404633/41101901-240e5b28-6a6e-11e8-8e76-8d3641b751b5.png)

**Comment by kennenfromchina** [comment]
How to use FlexLayout to layout self-height UITextView？
