### ISSUE TITLE
Remove Item using Flex

### ISSUE THREAD

**Issue by aravind694** [layoutBox/FlexLayout#98]
how to remove an item in flex like removeFromSuperView() - is not an issue, need suggestion

**Comment by darkhandz** [comment]
```
@objc func buttonClicked() {
    let hide = true
    addressLabel.flex.isIncludedInLayout = !hide
    addressLabel.isHidden = hide
    setNeedsLayout()
}
```

**Comment by lucdion** [comment]
@aravind694, you can still use `removeFromSuperview` to completely remove the view from the flex container and the superview.

**Comment by jordanebelanger** [comment]
`item.flex.display(.none)`
